         parameter(nc_p=100,nf_p=300,ncf_p=nc_p+nf_p+1)

         common/comfit/ rfit(nf_p),zfit(nf_p),rpre(nc_p),zpre(nc_p),
     *                 psifit(nf_p),psipre(nc_p),curref(nc_p),
     *                 w_wght(nf_p),d_wght(nc_p),s_wght,
     *                 Gindk(nc_p,nf_p),Gindp(nc_p,nf_p),
     *                 Gx_r(nc_p),Gx_z(nc_p),rx_p,zx_p,dpsx_r,dpsx_z,
     *                 Ginda(nc_p),Gindx(nc_p),psip_x,psip_a,
     *                 r_ax,z_ax,alph,Lfit,Lpre


 





