C======================================================================|
	subroutine TONEUT(JSBP)
C----------------------------------------------------------------------|
C Call of this subroutine is created by the Astra compiler
C The C-function to_neut_ fills shared memory segment Nr. (JSBP+1)
C Parameter JSBP is the ordinal number of the (&:) request in a model.
C           JSBP is generated by the Astra compiler.
C Arguments NNCX and SNNBM transfer addresses of astra common blocks
C     to the C-function to_neut_
C----------------------------------------------------------------------|
	implicit none
	integer JSBP
	include	'for/parameter.inc'
	include 'for/const.inc'
	include 'for/status.inc'
C----------------------------------------------------------------------|
	call	to_neut(JSBP,NNCX,SNNBM)
	end
C======================================================================|
	subroutine OTNEUT(JSBP,JSBR)
C----------------------------------------------------------------------|
C Call of this subroutine is created by the Astra compiler
C Parameter JSBP is the ordinal number of the (&:) request in a model
C Parameter JSBR is the ordinal number of the (:) request in a model
C           JSBR is needed to store the CPU times used by all 
C       	 processes and subroutines in a homogeneous way.
C           JSBP and JSBR are generated by the Astra compiler.
C
C Get NN, TN, ALBPL and CPU usage time from shared memory via ot_neut
C----------------------------------------------------------------------|
	implicit none
	integer JSBP,JSBR
	include	'for/parameter.inc'
	include 'for/const.inc'
	include 'for/status.inc'
	include 'for/outcmn.inc'
C----------------------------------------------------------------------|
	call	ot_neut(JSBP,NN,TN,ALBPL,CPTSBR(JSBR))
	end
C======================================================================|
